version: 2
updates:

  # Config for backend-dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      backend-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # Config for docker-compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      docker-compose:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
