// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import io.miragon.bpmn.runtime.MessageName
import kotlin.Suppress

/**
 * BPMN message names used to correlate messages to running process instances.
 */
object Messages {
  val MIRAVELO_CONFIRMATION_REJECTED: MessageName =
      MessageName("miravelo.confirmationRejected")

  val MIRAVELO_MEMBERSHIP_REQUESTED: MessageName =
      MessageName("miravelo.membershipRequested")
}
