// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import io.miragon.bpmn.runtime.MessageName
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN message names used to correlate messages to running process instances.
 */
object Messages {
  val MIRAVELO_CONFIRMATION_REJECTED: MessageName =
      MessageName("miravelo.confirmationRejected")

  val MIRAVELO_MEMBERSHIP_REQUESTED: MessageName =
      MessageName("miravelo.membershipRequested")

  val all: List<MessageName> = listOf(
    MIRAVELO_CONFIRMATION_REJECTED,
    MIRAVELO_MEMBERSHIP_REQUESTED,
  )
}
