// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import kotlin.String
import kotlin.Suppress

object MiraveloMembershipProcessApi {
  const val PROCESS_ID: String = "miravelo-membership"

  const val PROCESS_ENGINE: String = "ZEEBE"

  object Elements {
    const val END_EVENT_MEMBERSHIP_CONFIRMED: String = "endEvent_MembershipConfirmed"

    const val END_EVENT_MEMBERSHIP_REJECTED: String = "endEvent_MembershipRejected"

    const val GATEWAY_HAS_EMPTY_SPOTS: String = "gateway_HasEmptySpots"

    const val RECEIVE_TASK_CONFIRM_MEMBERSHIP: String = "receiveTask_ConfirmMembership"

    const val SERVICE_TASK_CLAIM_MEMBERSHIP: String = "serviceTask_ClaimMembership"

    const val SERVICE_TASK_SEND_CONFIRMATION_MAIL: String =
        "serviceTask_SendConfirmationMail"

    const val SERVICE_TASK_SEND_REJECTION_MAIL: String = "serviceTask_SendRejectionMail"

    const val SERVICE_TASK_SEND_WELCOME_MAIL: String = "serviceTask_SendWelcomeMail"

    const val START_EVENT_MEMBERSHIP_FORM_SUBMITTED: String =
        "startEvent_MembershipFormSubmitted"
  }

  object Messages {
    const val MIRAVELO_MEMBERSHIP_CONFIRMED: String = "miravelo.membershipConfirmed"
  }

  object TaskTypes {
    const val MIRAVELO_CLAIM_MEMBERSHIP: String = "miravelo.claimMembership"

    const val MIRAVELO_SEND_CONFIRMATION_MAIL: String = "miravelo.sendConfirmationMail"

    const val MIRAVELO_SEND_REJECTION_MAIL: String = "miravelo.sendRejectionMail"

    const val MIRAVELO_SEND_WELCOME_MAIL: String = "miravelo.sendWelcomeMail"
  }

  object Variables {
    const val HAS_EMPTY_SPOTS: String = "hasEmptySpots"

    const val MEMBERSHIP_ID: String = "membershipId"
  }
}
