// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionProcessApi {
  const val PROCESS_ID: String = "newsletter-subscription"

  const val PROCESS_ENGINE: String = "ZEEBE"

  object Elements {
    const val END_EVENT_REGISTRATION_ABORTED: String = "endEvent_RegistrationAborted"

    const val END_EVENT_REGISTRATION_COMPLETED: String = "endEvent_RegistrationCompleted"

    const val END_EVENT_SUBSCRIPTION_CONFIRMED: String = "endEvent_SubscriptionConfirmed"

    const val EVENT_AFTER_3_DAYS: String = "event_After3Days"

    const val EVENT_EVERY_DAY: String = "event_EveryDay"

    const val RECEIVE_TASK_CONFIRM_REGISTRATION: String = "receiveTask_ConfirmRegistration"

    const val SERVICE_TASK_ABORT_REGISTRATION: String = "serviceTask_AbortRegistration"

    const val SERVICE_TASK_SEND_CONFIRMATION_MAIL: String =
        "serviceTask_SendConfirmationMail"

    const val SERVICE_TASK_SEND_WELCOME_MAIL: String = "serviceTask_SendWelcomeMail"

    const val START_EVENT_REQUEST_RECEIVED: String = "startEvent_RequestReceived"

    const val START_EVENT_SUBMIT_REGISTRATION_FORM: String =
        "startEvent_SubmitRegistrationForm"

    const val SUB_PROCESS_CONFIRM_SUBSCRIPTION: String = "subProcess_ConfirmSubscription"
  }

  object Messages {
    const val NEWSLETTER_SUBSCRIPTION_CONFIRMED: String = "newsletter.subscriptionConfirmed"
  }

  object TaskTypes {
    const val NEWSLETTER_ABORT_REGISTRATION: String = "newsletter.abortRegistration"

    const val NEWSLETTER_SEND_CONFIRMATION_MAIL: String = "newsletter.sendConfirmationMail"

    const val NEWSLETTER_SEND_WELCOME_MAIL: String = "newsletter.sendWelcomeMail"
  }

  object Timers {
    val EVENT_AFTER_3_DAYS: BpmnTimer = BpmnTimer("Duration", "PT2M30S")

    val EVENT_EVERY_DAY: BpmnTimer = BpmnTimer("Duration", "PT1M")

    data class BpmnTimer(
      val type: String,
      val timerValue: String,
    )
  }

  object Variables {
    const val SUBSCRIPTION_ID: String = "subscriptionId"

    const val WELCOME_MAIL_SENT: String = "welcomeMailSent"
  }
}
