// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionProcessApi {
  const val PROCESS_ID: String = "newsletter-subscription"

  const val PROCESS_ENGINE: String = "ZEEBE"

  object Elements {
    const val ACTIVITY_ABORT_REGISTRATION: String = "Activity_AbortRegistration"

    const val ACTIVITY_CONFIRM_REGISTRATION: String = "Activity_ConfirmRegistration"

    const val ACTIVITY_SEND_CONFIRMATION_MAIL: String = "Activity_SendConfirmationMail"

    const val ACTIVITY_SEND_WELCOME_MAIL: String = "Activity_SendWelcomeMail"

    const val END_EVENT_REGISTRATION_ABORTED: String = "EndEvent_RegistrationAborted"

    const val END_EVENT_REGISTRATION_COMPLETED: String = "EndEvent_RegistrationCompleted"

    const val END_EVENT_SUBSCRIPTION_CONFIRMED: String = "EndEvent_SubscriptionConfirmed"

    const val START_EVENT_REQUEST_RECEIVED: String = "StartEvent_RequestReceived"

    const val START_EVENT_SUBMIT_REGISTRATION_FORM: String =
        "StartEvent_SubmitRegistrationForm"

    const val SUB_PROCESS_CONFIRM_SUBSCRIPTION: String = "SubProcess_ConfirmSubscription"

    const val TIMER_AFTER_3_DAYS: String = "Timer_After3Days"

    const val TIMER_EVERY_DAY: String = "Timer_EveryDay"
  }

  object Messages {
    const val MESSAGE_FORM_SUBMITTED: String = "Message_FormSubmitted"

    const val MESSAGE_SUBSCRIPTION_CONFIRMED: String = "Message_SubscriptionConfirmed"
  }

  object TaskTypes {
    const val NEWSLETTER_ABORT_REGISTRATION: String = "newsletter.abortRegistration"

    const val NEWSLETTER_SEND_CONFIRMATION_MAIL: String = "newsletter.sendConfirmationMail"

    const val NEWSLETTER_SEND_WELCOME_MAIL: String = "newsletter.sendWelcomeMail"
  }

  object Timers {
    val TIMER_AFTER_3_DAYS: BpmnTimer = BpmnTimer("Duration", "PT2M30S")

    val TIMER_EVERY_DAY: BpmnTimer = BpmnTimer("Duration", "PT1M")

    data class BpmnTimer(
      val type: String,
      val timerValue: String,
    )
  }

  object Variables {
    const val SUBSCRIPTION_ID: String = "subscriptionId"
  }
}
