// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Names of the process variables used in `@Variable(name = ProcessVariables.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ProcessVariables {
  const val HAS_EMPTY_SPOTS: String = "hasEmptySpots"

  const val MEMBERSHIP_ID: String = "membershipId"

  val all: List<String> = listOf(
    HAS_EMPTY_SPOTS,
    MEMBERSHIP_ID,
  )
}
