// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ServiceTasks {
  const val MIRAVELO_CLAIM_MEMBERSHIP: String = "miravelo.claimMembership"

  const val MIRAVELO_RE_SEND_CONFIRMATION_MAIL: String = "miravelo.reSendConfirmationMail"

  const val MIRAVELO_REVOKE_CLAIM: String = "miravelo.revokeClaim"

  const val MIRAVELO_REVOKE_MEMBERSHIP_REQUEST: String = "miravelo.revokeMembershipRequest"

  const val MIRAVELO_SEND_CONFIRMATION_MAIL: String = "miravelo.sendConfirmationMail"

  const val MIRAVELO_SEND_REJECTION_MAIL: String = "miravelo.sendRejectionMail"

  const val MIRAVELO_SEND_WELCOME_MAIL: String = "miravelo.sendWelcomeMail"

  val entries: List<String> = listOf(
    MIRAVELO_CLAIM_MEMBERSHIP,
    MIRAVELO_RE_SEND_CONFIRMATION_MAIL,
    MIRAVELO_REVOKE_CLAIM,
    MIRAVELO_REVOKE_MEMBERSHIP_REQUEST,
    MIRAVELO_SEND_CONFIRMATION_MAIL,
    MIRAVELO_SEND_REJECTION_MAIL,
    MIRAVELO_SEND_WELCOME_MAIL,
  )
}
