// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import io.miragon.bpmn.runtime.SignalName
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN signal names broadcast and caught by signal events.
 */
object Signals {
  val MIRAVELO_MEMBERSHIP_ACTIVATED: SignalName =
      SignalName(Names.MIRAVELO_MEMBERSHIP_ACTIVATED)

  val entries: List<SignalName> = listOf(
    MIRAVELO_MEMBERSHIP_ACTIVATED,
  )

  object Names {
    const val MIRAVELO_MEMBERSHIP_ACTIVATED: String = "miravelo.membershipActivated"
  }
}
