// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.example.adapter.process

import io.miragon.bpmn.runtime.SignalName
import kotlin.Suppress

/**
 * BPMN signal names broadcast and caught by signal events.
 */
object Signals {
  val MIRAVELO_MEMBERSHIP_ACTIVATED: SignalName = SignalName("miravelo.membershipActivated")
}
