name: Bug Report
description: Report a bug or unexpected behaviour in easy-zeebe
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill in the details below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I start the newsletter subscription process, the confirmation mail worker throws an exception...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the behaviour.
      placeholder: |
        1. Start the application with `./gradlew :services:example-service:bootRun`
        2. Submit a subscription via the frontend
        3. Observe the following error in logs...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened? Include logs, stack traces, or screenshots if relevant.
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      placeholder: "21"
    validations:
      required: false

  - type: input
    id: zeebe-version
    attributes:
      label: Zeebe / Camunda Platform Version
      placeholder: "8.8"
    validations:
      required: false

  - type: input
    id: module
    attributes:
      label: Affected Module
      placeholder: "example-service / common-zeebe / common-zeebe-test"
    validations:
      required: false
