name: Refactor
description: Propose a code refactoring or structural improvement
title: "[Refactor]: "
labels:
  - refactor
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a refactoring! Please describe the current state, the target state, and the motivation.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What will be refactored and why?
      placeholder: Extract the Zeebe client configuration into a dedicated auto-configuration module so it can be reused across services.
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current implementation and its shortcomings.
      placeholder: |
        The Zeebe client is currently configured inline in `ZeebeConfiguration.kt`. This makes it hard to reuse the same configuration in other services without copy-pasting.
    validations:
      required: true

  - type: textarea
    id: target-state
    attributes:
      label: Target State
      description: Describe what the code should look like after the refactoring.
      placeholder: |
        A new `common-zeebe-autoconfigure` module provides a Spring Boot auto-configuration that any service can depend on. The `example-service` uses this module instead of configuring Zeebe manually.
    validations:
      required: true

  - type: textarea
    id: out-of-scope
    attributes:
      label: Out of Scope
      description: What will NOT be changed by this refactor?
      placeholder: The BPMN process definitions and business logic remain untouched.
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Risks / Considerations
      description: Any breaking changes, migration steps, or risks to be aware of?
    validations:
      required: false
