// Generated by bpmn-to-code
@file:Suppress("unused")

package de.emaarco.example.adapter.process

import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionProcessApi {
  const val PROCESS_ID: String = "newsletter-subscription"

  object Elements {
    const val Timer_After3Days: String = "Timer_After3Days"

    const val Timer_EveryDay: String = "Timer_EveryDay"

    const val Activity_ConfirmRegistration: String = "Activity_ConfirmRegistration"

    const val SubProcess_ConfirmSubscription: String = "SubProcess_ConfirmSubscription"

    const val EndEvent_RegistrationAborted: String = "EndEvent_RegistrationAborted"

    const val EndEvent_RegistrationCompleted: String = "EndEvent_RegistrationCompleted"

    const val EndEvent_SubscriptionConfirmed: String = "EndEvent_SubscriptionConfirmed"

    const val Activity_AbortRegistration: String = "Activity_AbortRegistration"

    const val Activity_SendWelcomeMail: String = "Activity_SendWelcomeMail"

    const val Activity_SendConfirmationMail: String = "Activity_SendConfirmationMail"

    const val StartEvent_RequestReceived: String = "StartEvent_RequestReceived"

    const val StartEvent_SubmitRegistrationForm: String = "StartEvent_SubmitRegistrationForm"
  }

  object Messages {
    const val Message_FormSubmitted: String = "Message_FormSubmitted"

    const val Message_SubscriptionConfirmed: String = "Message_SubscriptionConfirmed"
  }

  object TaskTypes {
    const val Activity_AbortRegistration: String = "newsletter.abortRegistration"

    const val Activity_SendWelcomeMail: String = "newsletter.sendWelcomeMail"

    const val Activity_SendConfirmationMail: String = "newsletter.sendConfirmationMail"
  }

  object Timers {
    val Timer_After3Days: BpmnTimer = BpmnTimer("Duration", "PT2M30S")

    val Timer_EveryDay: BpmnTimer = BpmnTimer("Duration", "PT1M")

    data class BpmnTimer(
      val type: String,
      val timerValue: String,
    )
  }
}
