server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easy-zeebe
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
