# Use this only in dev environments. It's not intended for production usage.
services:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: easy-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: easy-zeebe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  zeebe:
    image: camunda/zeebe:${CAMUNDA_PLATFORM_VERSION}
    container_name: easy-zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE: ${ZEEBE_AUTHENTICATION_MODE}
      ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME: io.camunda.zeebe.exporter.ElasticsearchExporter
      ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL: http://elasticsearch:9200
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m"
      ZEEBE_LOG_LEVEL: debug
    restart: always
    networks:
      - camunda-platform
    depends_on:
      elasticsearch:
        condition: service_healthy

  operate:
    image: camunda/operate:${CAMUNDA_PLATFORM_VERSION}
    container_name: easy-operate
    ports:
      - "9081:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - camunda-platform
    depends_on:
      zeebe:
        condition: service_started
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: bitnami/elasticsearch:${ELASTIC_VERSION}
    container_name: easy-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elastic:/bitnami/elasticsearch/data"
    healthcheck:
      # In local environments, we allow both green and yellow health statuses.
      # Yellow means the cluster is operational, but some replicas are unassigned.
      # This carries a risk of data loss if a node fails but is acceptable for local development.
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -Eq 'green|yellow'" ]
      interval: 1s
      retries: 90
    networks:
      - camunda-platform

volumes:
  elastic:

networks:
  camunda-platform:
