# Use this only in dev environments. It's not intended for production usage.
services:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: easy-postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: example_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  # Consolidated Zeebe + Operate + Tasklist - https://docs.camunda.io/docs/self-managed/setup/deploy/other/docker/#zeebe
  orchestration:
    image: camunda/camunda:${CAMUNDA_VERSION}
    container_name: easy-zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8088:8080"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9600 && echo -e \"GET /actuator/health/status HTTP/1.1\r\nHost: localhost\r\n\r\n\" >&3 && head -n 1 <&3'" ]
      interval: 1s
      retries: 30
      start_period: 30s
    volumes:
      - zeebe:/usr/local/zeebe/data
    configs:
      - source: orchestration-config
        target: /usr/local/camunda/config/application.yaml
    networks:
      - camunda
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: bitnami/elasticsearch:${ELASTIC_VERSION}
    container_name: easy-elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elastic:/bitnami/elasticsearch/data'
    healthcheck:
      # In local environments, we allow both green and yellow health statuses.
      # Yellow means the cluster is operational, but some replicas are unassigned.
      # This carries a risk of data loss if a node fails but is acceptable for local development.
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -Eq 'green|yellow'" ]
      interval: 1s
      retries: 90
    networks:
      - camunda

volumes:
  elastic:
  zeebe:

networks:
  camunda:

configs:

  orchestration-config:
    content: |
      management.endpoints.configprops.show-values: always
      camunda:
        system:
          cpu-thread-count: "3"
          io-thread-count: "3"
        security:
          authentication:
            method: "basic"
            unprotectedApi: true
          authorizations:
            enabled: false
          initialization:
            users:
              - username: "demo"
                password: "demo"
                name: "Demo User"
                email: "demo@demo.com"
            defaultRoles.admin.users:
              - "demo"
        database.index.numberOfReplicas: 0 # Single node elasticsearch so we disable replication
        data:
          secondary-storage:
            type: elasticsearch
            elasticsearch:
              cluster-name: elasticsearch
              url: "http://elasticsearch:9200"
